// <auto-generated />
using System;
using CryptoEvaluator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoEvaluator.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Atr")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("AverageVolume")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("Ema20")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("Ema200")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("Ema50")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("Rsi")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Volume")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("VolumeRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("strategies", (string)null);
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.StrategyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("strategy_rules", (string)null);
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountBalance")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("RiskPercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TakeProfit")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<int>("Timeframe")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.TradeEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<decimal>("MarginRequired")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("PositionSize")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("RiskAmount")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("RiskRewardRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("trade_evaluations", (string)null);
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.TradePrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExpectedRMultiple")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("LossProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("NoHitProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("RandomSeed")
                        .HasColumnType("integer");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WinProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("trade_predictions", (string)null);
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.TradeResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsWin")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Pnl")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal>("RMultiple")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("trade_results", (string)null);
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.MarketSnapshot", b =>
                {
                    b.HasOne("CryptoEvaluator.Domain.Entities.Trade", null)
                        .WithOne("LatestSnapshot")
                        .HasForeignKey("CryptoEvaluator.Domain.Entities.MarketSnapshot", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.StrategyRule", b =>
                {
                    b.HasOne("CryptoEvaluator.Domain.Entities.Strategy", null)
                        .WithMany("Rules")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.TradeEvaluation", b =>
                {
                    b.HasOne("CryptoEvaluator.Domain.Entities.Trade", null)
                        .WithOne("LatestEvaluation")
                        .HasForeignKey("CryptoEvaluator.Domain.Entities.TradeEvaluation", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.TradePrediction", b =>
                {
                    b.HasOne("CryptoEvaluator.Domain.Entities.Trade", null)
                        .WithOne("LatestPrediction")
                        .HasForeignKey("CryptoEvaluator.Domain.Entities.TradePrediction", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.TradeResult", b =>
                {
                    b.HasOne("CryptoEvaluator.Domain.Entities.Trade", null)
                        .WithOne("Result")
                        .HasForeignKey("CryptoEvaluator.Domain.Entities.TradeResult", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.Strategy", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("CryptoEvaluator.Domain.Entities.Trade", b =>
                {
                    b.Navigation("LatestEvaluation");

                    b.Navigation("LatestPrediction");

                    b.Navigation("LatestSnapshot");

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
